mod eventgen;

mod gridfuncs;

#[macro_use]
extern crate ndarray;
#[macro_use]
extern crate lazy_static;
extern crate ordered_float;
extern crate rand;
extern crate revord;

use ordered_float::*;

fn main() {
    unsafe {
        // 'event.time' was just generated by one of the 'event_*' functions
        // and cannot be NaN
        let t1: NotNaN<f32> = NotNaN::unchecked_new(2.0);
        let t2: NotNaN<f32> = NotNaN::unchecked_new(2.0);
        println!("{}", t1 < t2);
        println!("{}", t1 > t2);
        println!("{}", t1 == t2);
    }
}
